### ISSUE TITLE
Healthchecks check for both externalIP & internalIP of each control plane node

### ISSUE THREAD

**Issue by clrxbl** [kubernetes-sigs/cloud-provider-equinix-metal#170]
I want to be able to set the bind-address of my control plane nodes to their VLAN / private network IP. I am currently unable to because it checks for both the external & internal IP address of my control plane nodes.

**Comment by deitch** [comment]
@clrxbl why does it matter? If you are bound to just 1 address, it will check the others, fail on those, but find the working one. The healthcheck will take whatever one it finds.
