### ISSUE TITLE
Tollerate new control-plane node node labels

### ISSUE THREAD

**Issue by displague** [kubernetes-sigs/cloud-provider-equinix-metal#341]
The `master` toleration is outdated. The new toleration should be for `node-role.kubernetes.io/control-plane`.
https://kubernetes.io/docs/reference/labels-annotations-taints/

**Comment by ctreatma** [comment]
Seems like this was done in #209?

**Comment by displague** [comment]
If not there, then #211 

https://github.com/search?q=repo%3Akubernetes-sigs%2Fcloud-provider-equinix-metal%20master&type=code
