### ISSUE TITLE
critical-pod is non functional in 1.16+, use priorityClassName instead

### ISSUE THREAD

**Issue by displague** [kubernetes-sigs/cloud-provider-equinix-metal#342]
`spec.template.metadata.annotations scheduler.alpha.kubernetes.io/critical-pod` is non functional in 1.16+, use `priorityClassName` instead

https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/

**Comment by ctreatma** [comment]
Seems like this was addressed in #310?
