### ISSUE TITLE
CPEM fails with Talos linux

### ISSUE THREAD

**Issue by KrystianMarek** [kubernetes-sigs/cloud-provider-equinix-metal#398]
CPEM installed in k8s cluster deployed on Talos linux, with [instructions](https://github.com/KrystianMarek/talos-on-equinix-metal#benchmark)
Fails with [error](https://github.com/KrystianMarek/talos-on-equinix-metal/issues/4).

**Comment by cprivitere** [comment]
It's unclear what the error is. You linked a closed issue. Also did you remove the external cloud provider setting? CPEM needs that.
