### ISSUE TITLE
Replace packngo with metal-go

### ISSUE THREAD

**Issue by displague** [kubernetes-sigs/cloud-provider-equinix-metal#439]
https://github.com/equinix-labs/metal-go is an OAS3 generated SDK that is the successor to the hand curated https://github.com/packethost/packngo SDK.

The latter is being deprecated once key integrations including this project, https://github.com/kubernetes-sigs/cluster-api-provider-packet/pull/527, metal-cli, and terraform-provider-equinix have successfully adopted the new SDK (thus proving its completeness and accuracy).  

Related to https://github.com/equinix-labs/metal-go/issues/99

**Comment by ctreatma** [comment]
Just noting here, `packngo` was instead replaced with [`equinix-sdk-go`](https://github.com/equinix/equinix-sdk-go) because that SDK is roughly identical to `metal-go` and is maintained (`metal-go` was experimental and is now deprecated itself).
